<?xml version="1.0"?>
<package format="3">
  <name>tl_hardware</name>
  <version>0.0.1</version>
  <description>ROS2 control hardware interface for TL robot arm</description>

  <maintainer email="tl@robot.com">your_name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tl_ros2_interface</depend>
  <depend>trajectory_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
    <hardware_interface plugin="${prefix}/tl_hardware_interface.xml"/>
  </export>
</package>