# 机器人DH参数
float64 l1
float64 l2
float64 l3
float64 l4
float64 l5
float64 l6
float64 l7
float64 l8
float64 l9
float64 l10
float64 l11
float64 l12
float64 l13
float64 l14
float64 l15
float64 l16
float64 l17
float64 l18
float64 l19
float64 l20

float64 couple_coe_1_2
float64 couple_coe_2_3
float64 couple_coe_3_2
float64 couple_coe_3_4
float64 couple_coe_4_5
float64 couple_coe_4_6
float64 couple_coe_5_6

float64 dynamic_limit_max
float64 dynamic_limit_min

float64 pitch
float64 sliding_lead_value
float64 uplift_lead_value
float64 spray_distance

float64 three_axis_direction
float64 five_axis_direction

float64	two_axis_convertion_ratio
float64 three_axis_convertion_ratio
float64 amplification_ratio

float64 convertion_ratio_x
float64 convertion_ratio_y
float64 convertion_ratio_z

float64 convertion_ratio_j1
float64 convertion_ratio_j2
float64 convertion_ratio_j3

int32 upside_down

float64 pc
float64[] sp
float64[] tl

